# Generated by Django 5.0.4 on 2024-04-15 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('bank_name', models.CharField(max_length=255)),
            ],
        ),
    ]
