# Generated by Django 5.0.4 on 2024-04-15 14:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_rename_banco_instituicao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='instituicao',
            old_name='codigo_compensacao',
            new_name='CodigoCompensacao',
        ),
        migrations.RenameField(
            model_name='instituicao',
            old_name='bank_name',
            new_name='NomeInstituicao',
        ),
    ]
