# Generated by Django 5.0.4 on 2024-04-15 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_rename_codigo_compensacao_instituicao_codigocompensacao_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='instituicao',
            name='CodigoCompensacao',
            field=models.IntegerField(db_column='CodigoCompensacao', primary_key=True, serialize=False),
        ),
        migrations.RenameField(
            model_name='instituicao',
            old_name='CodigoCompensacao',
            new_name='codigo_compensacao',
        ),
        migrations.AlterField(
            model_name='instituicao',
            name='NomeInstituicao',
            field=models.CharField(db_column='NomeInstituicao', max_length=255),
        ),
        migrations.RenameField(
            model_name='instituicao',
            old_name='NomeInstituicao',
            new_name='nome_instituicao',
        ),
    ]
