# Generated by Django 5.0.4 on 2024-04-15 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_instituicao_codigocompensacao_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Instituicao',
            new_name='MyappInstituicao',
        ),
        migrations.AlterModelOptions(
            name='myappinstituicao',
            options={'managed': True},
        ),
        migrations.RenameField(
            model_name='myappinstituicao',
            old_name='codigo_compensacao',
            new_name='codigocompensacao',
        ),
        migrations.RenameField(
            model_name='myappinstituicao',
            old_name='nome_instituicao',
            new_name='nomeinstituicao',
        ),
        migrations.AlterModelTable(
            name='myappinstituicao',
            table='myapp_instituicao',
        ),
    ]
